language: node_js
node_js:
  - "8"

before_install:
  - "npm install -g purescript typescript pulp bower uglify-es"

script:
  - make

cache:
  directories:
    - "build"
    - "purescript/bower_components"
    - "purescript/output"
  timeout: 3600
