language: node_js
node_js:
  - "8"

before_install:
  - "npm install"

script:
  - "npm run make"
  - "npm test"

cache:
  directories:
    - "build"
    - "purescript/bower_components"
    - "purescript/output"
  timeout: 3600
